name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: free60/libxenon:latest

    steps:
    - uses: actions/checkout@v2
    - name: Ensure environment exports
      run: source /etc/profile.d/99-devkitxenon.sh
    - name: Build
      run: make
    - name: Build (dist)
      run: make dist
    - uses: actions/upload-artifact@v2
      with:
        name: XeLL-binaries
        path: XeLL_Reloaded-2stages-*.tar.gz
